# Generated by Django 3.2 on 2021-04-14 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210414_0930'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='unique username',
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
